import Head from 'next/head';

export const MainLayout = (props: any) => {
    return (
        <div className="dark dark:bg-gray-800 leading-tight min-h-screen flex flex-col max-height-hidden">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/*
            <main className="h-20 p-2 bg-gray-900 filter brightness-125 border-b border-indigo-900">
                <h1 className="text-gray-900 dark:text-gray-400">menu</h1>
            </main>
            */}

            <main className="h-full max-height-hidden">
                <div className="h-full max-height-hidden text-gray-600 dark:text-gray-300">
                    {props.children}
                </div>
            </main>

            {/*
            <footer className="h-10 bg-gray-900 filter brightness-125 p-2 border-t border-indigo-900">
                <small className="text-gray-900 dark:text-gray-500">
                    Powered by me
                </small>
            </footer>
            */}
        </div>
    );
};
